services:
  - type: web
    name: famchores
    env: node
    buildCommand: npm install
    startCommand: npm run setup:prod && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 5
    healthCheckPath: /health
    autoDeploy: true
